apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
    - image: leeroy-app
      context: leeroy-app
test:
  - image: leeroy-web
    structureTests:
      - ./leeroy-web/test/*
  - image: leeroy-app
    structureTests:
      - ./leeroy-app/test/*
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/*
      - leeroy-app/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
